FROM node:18

WORKDIR /app

COPY ./index.js ./index.js
COPY ./schemas ./schemas
COPY ./middleware ./middleware
COPY ./routes ./routes
COPY ./utils ./utils
COPY ./package.json ./package.json
# COPY ./env ./env

RUN npm install

EXPOSE 5000

CMD ["node", "index.js"]