services:
  frontend:
    ports:
      - '3000:3000'

    build:
      dockerfile: Dockerfile.reactUI
      context: ./frontend

    depends_on:
      - backend   


  backend: 
    ports: 
      - '5000:5000' 

    build:
      dockerfile: Dockerfile.node
      context: ./backend
      
    env_file:
      - ./backend/.env